version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DD_AGENT_MAJOR_VERSION=7
      - DD_API_KEY=82ed2d6337f64ba763f05367abebc163
      - DD_SITE=us5.datadoghq.com
