version: '3'
services:
  app:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_ENV=production
      - DD_SERVICE=your-service-name
      - DD_VERSION=1.0.0
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE}
    depends_on:
      - datadog-agent

  datadog-agent:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
